### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by agill59** [DSCI-310-2024/DSCI-310_predicting-shares_group-4#3]
In an attempt to create a safe, positive, productive, and happy community, many organizations and developers create a code of conduct for their projects. A code of conduct in a Data Science project informs others of social norms, acceptable behaviour and general etiquette. It is more outward facing than the team work contract discussed above. We recommend [Project Include](https://projectinclude.org/writing_cocs) for a comprehensive guide to writing an effective Code of Conduct.

At minimum, we believe that a good/effective code of conduct should include:

- A Statement on diversity and inclusivity
- Details on expected, and unacceptable behaviour
- A list of consequences for unacceptable behaviour
- A procedure for reporting and dealing with unacceptable behaviour

**Comment by anshnoorkaur** [comment]
A code-of-conduct branch has been created with details about this area with a pull request that awaits review and a go-ahead for merging.
