### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by agill59** [DSCI-310-2024/DSCI-310_predicting-shares_group-4#4]
It is a good practice to include information about how others, outside the core team, can contribute to your project somewhere in your repository. This is typically done as a separate file in the repository called CONTRIBUTING.md. Here are some examples of this file:

- [Altair](https://github.com/altair-viz/altair/blob/master/CONTRIBUTING.md)
- [dplyr](https://github.com/tidyverse/dplyr/blob/master/.github/CONTRIBUTING.md)
- [Atom editor](https://github.com/atom/atom/blob/master/CONTRIBUTING.md) (very comprehensive)

**Comment by anshnoorkaur** [comment]
Details have been added for this file in the contributing branch. A pull request has been created and awaits review.
