### ISSUE TITLE
Make file targe clarification (Milestone 2 feedback)

### ISSUE THREAD

**Issue by agill59** [DSCI-310-2024/DSCI-310_predicting-shares_group-4#50]
-1.5 the path to the report is wrong. you qmd file was not under docs/
-4 all files([plots, tables, csv ...) should being generated by the scripts should be added after all: in your make file

**Comment by anshnoorkaur** [comment]
qmd file is now under docs/

**Comment by anshnoorkaur** [comment]
Added all relevant files to Makefile all: 
Created a pull request. Please review and merge, thanks!
