### ISSUE TITLE
Abstrast/Summary revision (Milestone 1 feedback)

### ISSUE THREAD

**Issue by agill59** [DSCI-310-2024/DSCI-310_predicting-shares_group-4#57]
From the TA:
You did have a summary in your report. However, you didn't clearly state the question. You were interested in a predictive question. The way you put up such a question should be like "Can the number of images, links and videos in an article predict the number of shares on an article published by Mashable over a period of two years?". You should also include one/two sentences of your findings and importance/limitations in the summary which was not found.
2. if you decided not to use ipynb file but qmd file, you shouldn't include the ipynb file in your M1 as well as other unnecessary and meaningless stuff, for example, articles.zip.

**Comment by anshnoorkaur** [comment]
Addressed this by adding the research question clearly in the prediction_report.qmd file (starting line 24) and by deleting unnecessary files.
